DROP PROCEDURE IF EXISTS PARAMOUT;
DELIMITER //
CREATE PROCEDURE PARAMOUT (IN TEST INT, OUT TEST2 INT)
BEGIN
	SELECT TEST*5 INTO TEST2;
END//

DELIMITER ;

CALL PARAMOUT (5, @OUTTEST);	# 5를 파라미터로 IN 후 연산된 25를 OUTTEST 지역변수에 할당
SELECT @OUTTEST;